name: ss-tech-interview
type: silverstripe
docroot: public
php_version: "8.3"
webserver_type: apache-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: false
hooks:
  post-start: # fix db permissions to allow unit tests to create test databases
    - exec: "mysql -uroot -proot -hdb -e \"GRANT ALL ON *.* TO 'db'@'%';\""
